package com.prostovpn.desktop

data class Strings(
    val tagline: String,
    val loginPlaceholder: String,
    val passwordPlaceholder: String,
    val signIn: String,
    val signingIn: String,
    val signInDone: String,
    val continueWithoutAccount: String,
    val errEmptyLogin: String,
    val errShortPassword: String,
    val errBadKey: String,
    val errNoKey: String,
    val errNoBackend: String,
    val errElevation: String,
    val errTunnel: String,
    val errUnsupportedOs: String,
    val termsPrefix: String,
    val termsLink: String,

    val connected: String,
    val connectingTxt: String,
    val disconnected: String,
    val tapToConnect: String,
    val chooseServer: String,

    val settings: String,
    val split: String,
    val splitDesc: String,
    val addFile: String,
    val kill: String,
    val killDesc: String,
    val autostart: String,
    val autostartDesc: String,
    val autoconnect: String,
    val autoconnectDesc: String,
    val logging: String,
    val loggingDesc: String,
    val language: String,
    val langName: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val yes: String,
    val no: String,

    val fileTitle: String,
    val fileDesc: String,
    val defaultMeta: String,
    val entries: String,
    val chooseFile: String,
    val del: String,
    val holdHint: String,
    val rightClickHint: String,
    val importError: String,

    val version: String,
    val tgTitle: String,
    val siteTitle: String,
    val faqTitle: String,
    val faqSub: String,
    val rateTitle: String,
    val rateSub: String,
    val privacy: String,
    val terms: String,

    val ms: String,
)

private val RU = Strings(
    tagline = "Свободный и безопасный интернет",
    loginPlaceholder = "Логин",
    passwordPlaceholder = "Пароль",
    signIn = "Войти",
    signingIn = "Подключение…",
    signInDone = "✓ Готово",
    continueWithoutAccount = "Продолжить без входа",
    errEmptyLogin = "Введите логин",
    errShortPassword = "Пароль слишком короткий",
    errBadKey = "Не удалось применить ключ. Проверьте ключ и попробуйте ещё раз",
    errNoKey = "Нет ключа доступа. Войдите с ключом vpn://, чтобы подключиться",
    errNoBackend = "Не найден компонент туннеля AmneziaWG. Переустановите приложение",
    errElevation = "Для подключения нужны права администратора",
    errTunnel = "Не удалось поднять туннель",
    errUnsupportedOs = "Подключение поддерживается только на Windows",
    termsPrefix = "Продолжая, вы принимаете ",
    termsLink = "условия сервиса",
    connected = "Подключено",
    connectingTxt = "Подключение…",
    disconnected = "Отключено",
    tapToConnect = "Нажмите, чтобы подключиться",
    chooseServer = "ВЫБЕРИТЕ СЕРВЕР",
    settings = "Настройки",
    split = "Раздельное туннелирование",
    splitDesc = "Обходит видимость VPN для РФ сервисов",
    addFile = "Добавить файл",
    kill = "Kill Switch",
    killDesc = "Блокировать интернет при обрыве VPN",
    autostart = "Автозапуск",
    autostartDesc = "Запускать приложение при старте устройства",
    autoconnect = "Автоподключение",
    autoconnectDesc = "Подключаться к VPN при запуске",
    logging = "Логирование",
    loggingDesc = "Сохранять журнал для диагностики",
    language = "Язык",
    langName = "Русский",
    logout = "Выйти из аккаунта",
    logoutConfirmTitle = "Уверены, что хотите выйти?",
    logoutConfirmMessage = "Для входа понадобится снова ввести данные аккаунта",
    yes = "Да",
    no = "Нет",
    fileTitle = "Файл туннелирования",
    fileDesc = "Список сайтов и приложений, которые идут через VPN. Форматы: .json или .txt — по одному домену или названию приложения на строку.",
    defaultMeta = "По умолчанию",
    entries = "записей",
    chooseFile = "Выбрать файл",
    del = "Удалить",
    holdHint = "Удерживайте файл, чтобы удалить его",
    rightClickHint = "Правый клик по файлу — удалить",
    importError = "Не удалось прочитать файл",
    version = "Версия 1.0.0",
    tgTitle = "Поддержка в Telegram",
    siteTitle = "Наш сайт",
    faqTitle = "Частые вопросы",
    faqSub = "Как настроить и решить проблемы",
    rateTitle = "Оценить приложение",
    rateSub = "App Store · Google Play",
    privacy = "Политика конфиденциальности",
    terms = "Условия",
    ms = "мс",
)

private val EN = Strings(
    tagline = "Free and secure internet",
    loginPlaceholder = "Login",
    passwordPlaceholder = "Password",
    signIn = "Sign in",
    signingIn = "Connecting…",
    signInDone = "✓ Done",
    continueWithoutAccount = "Continue without account",
    errEmptyLogin = "Enter your login",
    errShortPassword = "Password is too short",
    errBadKey = "Couldn't apply the key. Check it and try again",
    errNoKey = "No access key. Sign in with a vpn:// key to connect",
    errNoBackend = "AmneziaWG tunnel component not found. Reinstall the app",
    errElevation = "Administrator rights are required to connect",
    errTunnel = "Couldn't bring the tunnel up",
    errUnsupportedOs = "Connecting is supported on Windows only",
    termsPrefix = "By continuing you accept the ",
    termsLink = "terms of service",
    connected = "Connected",
    connectingTxt = "Connecting…",
    disconnected = "Disconnected",
    tapToConnect = "Tap to connect",
    chooseServer = "CHOOSE A SERVER",
    settings = "Settings",
    split = "Split tunneling",
    splitDesc = "Hides VPN usage from Russian services",
    addFile = "Add file",
    kill = "Kill Switch",
    killDesc = "Block internet if VPN drops",
    autostart = "Launch at startup",
    autostartDesc = "Open the app when the device starts",
    autoconnect = "Auto-connect",
    autoconnectDesc = "Connect to VPN on launch",
    logging = "Logging",
    loggingDesc = "Keep a diagnostics log",
    language = "Language",
    langName = "English",
    logout = "Log out",
    logoutConfirmTitle = "Sure you want to log out?",
    logoutConfirmMessage = "You'll need to enter your account details again",
    yes = "Yes",
    no = "No",
    fileTitle = "Tunneling file",
    fileDesc = "A list of sites and apps routed through the VPN. Formats: .json or .txt — one domain or app name per line.",
    defaultMeta = "Default",
    entries = "entries",
    chooseFile = "Choose file",
    del = "Delete",
    holdHint = "Press and hold a file to delete it",
    rightClickHint = "Right-click a file to delete it",
    importError = "Couldn't read the file",
    version = "Version 1.0.0",
    tgTitle = "Telegram support",
    siteTitle = "Our website",
    faqTitle = "FAQ",
    faqSub = "Setup and troubleshooting",
    rateTitle = "Rate the app",
    rateSub = "App Store · Google Play",
    privacy = "Privacy policy",
    terms = "Terms",
    ms = "ms",
)

fun strings(lang: String): Strings = if (lang == "en") EN else RU
