[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD) [^"]*(wp-login|wp-admin|xmlrpc\.php|phpmyadmin|/\.env|/\.git|/vendor/|/cgi-bin/|/\.aws|/\.ssh|\.php)[^"]*"
ignoreregex =
datepattern = \[%%d/%%b/%%Y:%%H:%%M:%%S %%z\]
