package com.prostovpn.app

data class Strings(
    val tagline: String,
    val loginPlaceholder: String,
    val passwordPlaceholder: String,
    val signIn: String,
    val signingIn: String,
    val signInDone: String,
    val continueWithoutAccount: String,
    val errEmptyLogin: String,
    val errShortPassword: String,
    val errBadKey: String,
    val termsPrefix: String,
    val termsLink: String,

    val connected: String,
    val connectingTxt: String,
    val disconnectingTxt: String,
    val disconnected: String,
    val tapToConnect: String,
    val chooseServer: String,
    val errNoHandshake: String,
    val errTunnelFailed: String,
    val errTunnelDropped: String,
    val errVpnDenied: String,
    val noticeRemoteSignout: String,

    // Подписка на главном экране: предупреждение и продление
    val trafficLowWarn: String,
    val expiresSoonWarn: String,
    val renew: String,
    val dayOne: String,
    val dayFew: String,
    val dayMany: String,
    val unitGb: String,
    val unitMb: String,

    val settings: String,
    val split: String,
    val splitDesc: String,
    val addFile: String,
    val autoconnect: String,
    val autoconnectDesc: String,
    val background: String,
    val backgroundDesc: String,
    val backgroundDone: String,
    val notifDisconnect: String,
    val language: String,
    val langName: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val yes: String,
    val no: String,

    val fileTitle: String,
    val fileDesc: String,
    val defaultMeta: String,
    val entries: String,
    val chooseFile: String,
    val del: String,
    val holdHint: String,
    val importError: String,

    // Обновление приложения
    val updateChecking: String,
    val updateNone: String,
    val updateCurrent: String,
    val updateAvailable: String,
    val updateButton: String,
    val updateDownloading: String,
    val updateInstalling: String,
    val updateFailed: String,
    val updateMandatory: String,

    val version: String,
    val tgTitle: String,
    val siteTitle: String,
    val faqTitle: String,
    val faqSub: String,
    val rateTitle: String,
    val rateSub: String,
    val privacy: String,
    val terms: String,

    val ms: String,
)

private val RU = Strings(
    tagline = "Свободный и безопасный интернет",
    loginPlaceholder = "Логин или ключ",
    passwordPlaceholder = "Пароль",
    signIn = "Войти",
    signingIn = "Подключение…",
    signInDone = "✓ Готово",
    continueWithoutAccount = "Продолжить без входа",
    errEmptyLogin = "Введите логин",
    errShortPassword = "Пароль слишком короткий",
    errBadKey = "Не удалось применить ключ. Проверьте ключ и попробуйте ещё раз",
    termsPrefix = "Продолжая, вы принимаете ",
    termsLink = "условия сервиса",
    connected = "Подключено",
    connectingTxt = "Подключение…",
    disconnectingTxt = "Отключение…",
    disconnected = "Отключено",
    tapToConnect = "Нажмите, чтобы подключиться",
    chooseServer = "ВЫБЕРИТЕ СЕРВЕР",
    errNoHandshake = "Сервер не отвечает. Попробуйте другой сервер или мобильный интернет вместо Wi-Fi",
    errTunnelFailed = "Не удалось поднять туннель. Проверьте ключ и разрешение на VPN",
    errTunnelDropped = "Соединение с VPN прервалось",
    errVpnDenied = "Android не дал разрешение на VPN. Нажмите «Подключиться» ещё раз и выберите «ОК»",
    noticeRemoteSignout = "Это устройство отключили в личном кабинете. Войдите снова, чтобы продолжить",
    trafficLowWarn = "Трафик заканчивается: осталось %s",
    expiresSoonWarn = "Подписка истекает через %s",
    renew = "Продлить",
    dayOne = "день",
    dayFew = "дня",
    dayMany = "дней",
    unitGb = "ГБ",
    unitMb = "МБ",
    settings = "Настройки",
    split = "Раздельное туннелирование",
    splitDesc = "Российские сервисы идут напрямую, мимо VPN",
    addFile = "Добавить файл",
    autoconnect = "Автоподключение",
    autoconnectDesc = "Подключаться к VPN при запуске",
    background = "Работа в фоне",
    backgroundDesc = "Huawei, Honor, Xiaomi и подобные оболочки выгружают приложение из памяти и обрывают VPN. Снимите ограничение — это разовое действие",
    backgroundDone = "Ограничений нет",
    notifDisconnect = "Отключить",
    language = "Язык",
    langName = "Русский",
    logout = "Выйти из аккаунта",
    logoutConfirmTitle = "Уверены, что хотите выйти?",
    logoutConfirmMessage = "Для входа понадобится снова ввести данные аккаунта",
    yes = "Да",
    no = "Нет",
    fileTitle = "Файл туннелирования",
    fileDesc = "Список сайтов и приложений, которые идут через VPN. Форматы: .json или .txt — по одному домену или названию приложения на строку.",
    defaultMeta = "По умолчанию",
    entries = "записей",
    chooseFile = "Выбрать файл",
    del = "Удалить",
    holdHint = "Удерживайте файл, чтобы удалить его",
    importError = "Не удалось прочитать файл",
    updateChecking = "Проверяем обновления…",
    updateNone = "Установлена последняя версия",
    updateCurrent = "Сейчас установлена %s",
    updateAvailable = "Доступна версия %s",
    updateButton = "Обновить",
    updateDownloading = "Скачиваем… %d%%",
    updateInstalling = "Проверяем и открываем установку…",
    updateFailed = "Обновиться не получилось — проверьте связь и попробуйте ещё раз",
    updateMandatory = "Без этого обновления VPN работать не будет",
    version = "Версия",
    tgTitle = "Telegram",
    siteTitle = "Наш сайт",
    faqTitle = "Частые вопросы",
    faqSub = "Как настроить и решить проблемы",
    rateTitle = "Оценить приложение",
    rateSub = "App Store · Google Play",
    privacy = "Политика конфиденциальности",
    terms = "Условия",
    ms = "мс",
)

private val EN = Strings(
    tagline = "Free and secure internet",
    loginPlaceholder = "Login or key",
    passwordPlaceholder = "Password",
    signIn = "Sign in",
    signingIn = "Connecting…",
    signInDone = "✓ Done",
    continueWithoutAccount = "Continue without account",
    errEmptyLogin = "Enter your login",
    errShortPassword = "Password is too short",
    errBadKey = "Couldn't apply the key. Check it and try again",
    termsPrefix = "By continuing you accept the ",
    termsLink = "terms of service",
    connected = "Connected",
    connectingTxt = "Connecting…",
    disconnectingTxt = "Disconnecting…",
    disconnected = "Disconnected",
    tapToConnect = "Tap to connect",
    chooseServer = "CHOOSE A SERVER",
    errNoHandshake = "The server isn't responding. The network may be blocking VPN — try another server or mobile data instead of Wi-Fi",
    errTunnelFailed = "Couldn't bring the tunnel up. Check the key and VPN permission",
    errTunnelDropped = "VPN connection dropped",
    errVpnDenied = "Android denied the VPN permission. Tap Connect again and choose OK",
    noticeRemoteSignout = "This device was disconnected in the account dashboard. Sign in again to continue",
    trafficLowWarn = "Traffic is running out: %s left",
    expiresSoonWarn = "Subscription expires in %s",
    renew = "Renew",
    dayOne = "day",
    dayFew = "days",
    dayMany = "days",
    unitGb = "GB",
    unitMb = "MB",
    settings = "Settings",
    split = "Split tunneling",
    splitDesc = "Hides VPN usage from Russian services",
    addFile = "Add file",
    autoconnect = "Auto-connect",
    autoconnectDesc = "Connect to VPN on launch",
    background = "Background activity",
    backgroundDesc = "Huawei, Honor, Xiaomi and similar skins unload the app from memory and drop the VPN. Lift the restriction — it's a one-time action",
    backgroundDone = "No restrictions",
    notifDisconnect = "Disconnect",
    language = "Language",
    langName = "English",
    logout = "Log out",
    logoutConfirmTitle = "Sure you want to log out?",
    logoutConfirmMessage = "You'll need to enter your account details again",
    yes = "Yes",
    no = "No",
    fileTitle = "Tunneling file",
    fileDesc = "A list of sites and apps routed through the VPN. Formats: .json or .txt — one domain or app name per line.",
    defaultMeta = "Default",
    entries = "entries",
    chooseFile = "Choose file",
    del = "Delete",
    holdHint = "Press and hold a file to delete it",
    importError = "Couldn't read the file",
    updateChecking = "Checking for updates…",
    updateNone = "You are on the latest version",
    updateCurrent = "Currently installed %s",
    updateAvailable = "Version %s is available",
    updateButton = "Update",
    updateDownloading = "Downloading… %d%%",
    updateInstalling = "Verifying and opening the installer…",
    updateFailed = "The update didn't go through — check your connection and try again",
    updateMandatory = "The VPN won't work without this update",
    version = "Version",
    tgTitle = "Telegram",
    siteTitle = "Our website",
    faqTitle = "FAQ",
    faqSub = "Setup and troubleshooting",
    rateTitle = "Rate the app",
    rateSub = "App Store · Google Play",
    privacy = "Privacy policy",
    terms = "Terms",
    ms = "ms",
)

fun strings(lang: String): Strings = if (lang == "en") EN else RU
