package com.prostovpn.app

data class Strings(
    val tagline: String,
    val loginPlaceholder: String,
    val passwordPlaceholder: String,
    val signIn: String,
    val signingIn: String,
    val signInDone: String,
    val continueWithoutAccount: String,
    val errEmptyLogin: String,
    val errShortPassword: String,
    val errBadKey: String,
    val termsPrefix: String,
    val termsLink: String,

    val connected: String,
    // Подпись под таймером, когда работает запасной протокол: человеку важно
    // знать, что он идёт другим путём — скорость и поведение отличаются.
    val viaBackup: String,
    val connectingTxt: String,
    val disconnectingTxt: String,
    val disconnected: String,
    val tapToConnect: String,
    val chooseServer: String,
    val errNoHandshake: String,
    val errTunnelFailed: String,
    val errTunnelDropped: String,
    val errVpnDenied: String,
    val errNoServers: String,
    val notifOffWarn: String,
    val noticeRemoteSignout: String,

    val trafficLowWarn: String,
    val expiresSoonWarn: String,
    val renew: String,
    val dayOne: String,
    val dayFew: String,
    val dayMany: String,
    val unitGb: String,
    val unitMb: String,

    val settings: String,
    val split: String,
    val splitDesc: String,
    val addFile: String,
    val autoconnect: String,
    val autoconnectDesc: String,
    val background: String,
    val backgroundDesc: String,
    val backgroundDone: String,
    val notifDisconnect: String,
    val language: String,
    val langName: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val yes: String,
    val no: String,

    val fileTitle: String,
    val fileDesc: String,
    val defaultMeta: String,
    val entries: String,
    val chooseFile: String,
    val del: String,
    val holdHint: String,
    val importError: String,

    val updateChecking: String,
    val updateNone: String,
    val updateCurrent: String,
    val updateAvailable: String,
    val updateButton: String,
    val updateDownloading: String,
    val updateInstalling: String,
    val updateFailed: String,
    val updateMandatory: String,

    val version: String,
    val tgTitle: String,
    val siteTitle: String,
    val faqTitle: String,
    val faqSub: String,
    val rateTitle: String,
    val rateSub: String,
    val privacy: String,
    val terms: String,

    val ms: String,

    // Вкладки и новые экраны редизайна.
    val tabConnect: String,
    val tabCountries: String,
    val tabProfile: String,
    val locationLabel: String,
    val subscriptionLabel: String,
    val downloaded: String,
    val uploaded: String,
    val perSession: String,
    val untilDate: String,
    val endsSoon: String,
    val connectingTitle: String,
    val checkingNode: String,
    val waitingNode: String,
    val errorTitle: String,
    val errorChip: String,
    val errorUnknown: String,
    val retry: String,
    val changeCountry: String,
    val bestServer: String,
    val bestServerSub: String,
    val countryTitle: String,
    val countrySub: String,
    val connect: String,
    val yourLogin: String,
    val copy: String,
    val copied: String,
    val cabinet: String,
    val cabinetSub: String,
    val notices: String,
    val noNotices: String,
    val theme: String,
    val themeDark: String,
    val themeLight: String,
    val sectionConnection: String,
    val sectionApp: String,
    val about: String,
    val supportHeadline: String,
    val supportHours: String,
    val writeTelegram: String,
    val mailTitle: String,
    val siteAndCabinet: String,
    val noInternet: String,
    val noInternetSub: String,
    val loginTitle: String,
    val loginSub: String,
    val loginField: String,
    val passwordField: String,
    val showPassword: String,
    val hidePassword: String,
    val register: String,
    val forgotPassword: String,
    val notificationsTitle: String,
    val notificationsDesc: String,
    val autostartTitle: String,
    val ping: String,
    val supportTitle: String,
    val applyDone: String,
    val splitShort: String,
    val guideTitle: String,
    val guideSub: String,
)

private val RU = Strings(
    tagline = "Свободный и безопасный интернет",
    loginPlaceholder = "Логин или ключ",
    passwordPlaceholder = "Пароль",
    signIn = "Войти",
    signingIn = "Подключение…",
    signInDone = "✓ Готово",
    continueWithoutAccount = "Продолжить без входа",
    errEmptyLogin = "Введите логин",
    errShortPassword = "Пароль слишком короткий",
    errBadKey = "Не удалось применить ключ. Проверьте ключ и попробуйте ещё раз",
    termsPrefix = "Продолжая, вы принимаете ",
    termsLink = "условия сервиса",
    connected = "Подключено",
    viaBackup = "запасной протокол",
    connectingTxt = "Подключение…",
    disconnectingTxt = "Отключение…",
    disconnected = "Не подключено",
    tapToConnect = "Нажмите, чтобы подключиться",
    chooseServer = "ВЫБЕРИТЕ СЕРВЕР",
    errNoHandshake = "Сервер не отвечает. Попробуйте другой сервер или мобильный интернет вместо Wi-Fi",
    errTunnelFailed = "Не удалось поднять туннель. Проверьте ключ и разрешение на VPN",
    errTunnelDropped = "Соединение с VPN прервалось",
    errVpnDenied = "Android не дал разрешение на VPN. Нажмите «Подключиться» ещё раз и выберите «ОК»",
    errNoServers = "Нет доступных серверов. Проверьте подписку в личном кабинете",
    notifOffWarn = "Уведомления отключены — без них VPN нельзя выключить из шторки. Нажмите, чтобы включить",
    noticeRemoteSignout = "Это устройство отключили в личном кабинете. Войдите снова, чтобы продолжить",
    trafficLowWarn = "Трафик заканчивается: осталось %s",
    expiresSoonWarn = "Подписка истекает через %s",
    renew = "Продлить",
    dayOne = "день",
    dayFew = "дня",
    dayMany = "дней",
    unitGb = "ГБ",
    unitMb = "МБ",
    settings = "Настройки",
    split = "Раздельное туннелирование",
    splitDesc = "Российские сервисы идут напрямую, мимо VPN",
    addFile = "Добавить файл",
    autoconnect = "Автоподключение",
    autoconnectDesc = "Подключаться к VPN при запуске",
    background = "Работа в фоне",
    backgroundDesc = "Huawei, Honor, Xiaomi и подобные оболочки выгружают приложение из памяти и обрывают VPN. Снимите ограничение — это разовое действие",
    backgroundDone = "Ограничений нет",
    notifDisconnect = "Отключить",
    language = "Язык",
    langName = "Русский",
    logout = "Выйти из аккаунта",
    logoutConfirmTitle = "Уверены, что хотите выйти?",
    logoutConfirmMessage = "Для входа понадобится снова ввести данные аккаунта",
    yes = "Да",
    no = "Нет",
    fileTitle = "Файл туннелирования",
    fileDesc = "Список IP-подсетей, которые идут мимо VPN. Форматы: .json или .txt — по одной записи вида 1.2.3.0/24 на строку.",
    defaultMeta = "По умолчанию",
    entries = "записей",
    chooseFile = "Выбрать файл",
    del = "Удалить",
    holdHint = "Удерживайте файл, чтобы удалить его",
    importError = "Не удалось прочитать файл",
    updateChecking = "Проверяем обновления…",
    updateNone = "Установлена последняя версия",
    updateCurrent = "Сейчас установлена %s",
    updateAvailable = "Доступна версия %s",
    updateButton = "Обновить",
    updateDownloading = "Скачиваем… %d%%",
    updateInstalling = "Проверяем и открываем установку…",
    updateFailed = "Обновиться не получилось — проверьте связь и попробуйте ещё раз",
    updateMandatory = "Без этого обновления VPN работать не будет",
    version = "Версия",
    tgTitle = "Telegram",
    siteTitle = "Наш сайт",
    faqTitle = "Частые вопросы",
    faqSub = "Как настроить и решить проблемы",
    rateTitle = "Оценить приложение",
    rateSub = "App Store · Google Play",
    privacy = "Политика конфиденциальности",
    terms = "Условия",
    ms = "мс",

    tabConnect = "Подключение",
    tabCountries = "Страны",
    tabProfile = "Профиль",
    locationLabel = "Локация",
    subscriptionLabel = "Подписка",
    downloaded = "Скачано",
    uploaded = "Отдано",
    perSession = "за сессию",
    untilDate = "до %s",
    endsSoon = "скоро закончится",
    connectingTitle = "Подключаем",
    checkingNode = "Проверяем узел · %s",
    waitingNode = "Ждём ответ узла…",
    errorTitle = "Не удалось подключиться",
    errorChip = "Ошибка",
    errorUnknown = "Сервер не отвечает",
    retry = "Попробовать снова",
    changeCountry = "Сменить страну",
    bestServer = "Лучший сервер",
    bestServerSub = "Выберем сами по скорости",
    countryTitle = "Страна",
    countrySub = "Выбранная страна запомнится",
    connect = "Подключиться",
    yourLogin = "Ваш логин",
    copy = "Копировать",
    copied = "Скопировано",
    cabinet = "Личный кабинет",
    cabinetSub = "Тарифы, устройства, друзья",
    notices = "Уведомления",
    noNotices = "Пока ничего нового",
    theme = "Тема",
    themeDark = "Тёмная",
    themeLight = "Светлая",
    sectionConnection = "ПОДКЛЮЧЕНИЕ",
    sectionApp = "ПРИЛОЖЕНИЕ",
    about = "О приложении",
    supportHeadline = "Ответим за 10 минут",
    supportHours = "Каждый день с 9:00 до 23:00 по Москве",
    writeTelegram = "Написать в Телеграм",
    mailTitle = "Почта",
    siteAndCabinet = "Сайт и кабинет",
    noInternet = "Нет интернета",
    noInternetSub = "Проверьте Wi-Fi или мобильную сеть",
    loginTitle = "Вход",
    loginSub = "Логин и пароль от кабинета",
    loginField = "Логин",
    passwordField = "Пароль",
    showPassword = "Показать",
    hidePassword = "Скрыть",
    register = "Регистрация",
    forgotPassword = "Забыли пароль?",
    notificationsTitle = "Уведомления",
    notificationsDesc = "Без них VPN нельзя выключить из шторки",
    autostartTitle = "Автозапуск при старте",
    ping = "мс",
    supportTitle = "Поддержка",
    applyDone = "Готово",
    splitShort = "Банки и Госуслуги мимо VPN",
    guideTitle = "Инструкция",
    guideSub = "Установка и настройка",
)

private val EN = Strings(
    tagline = "Free and secure internet",
    loginPlaceholder = "Login or key",
    passwordPlaceholder = "Password",
    signIn = "Sign in",
    signingIn = "Connecting…",
    signInDone = "✓ Done",
    continueWithoutAccount = "Continue without account",
    errEmptyLogin = "Enter your login",
    errShortPassword = "Password is too short",
    errBadKey = "Couldn't apply the key. Check it and try again",
    termsPrefix = "By continuing you accept the ",
    termsLink = "terms of service",
    connected = "Connected",
    viaBackup = "backup protocol",
    connectingTxt = "Connecting…",
    disconnectingTxt = "Disconnecting…",
    disconnected = "Not connected",
    tapToConnect = "Tap to connect",
    chooseServer = "CHOOSE A SERVER",
    errNoHandshake = "The server isn't responding. The network may be blocking VPN — try another server or mobile data instead of Wi-Fi",
    errTunnelFailed = "Couldn't bring the tunnel up. Check the key and VPN permission",
    errTunnelDropped = "VPN connection dropped",
    errVpnDenied = "Android denied the VPN permission. Tap Connect again and choose OK",
    errNoServers = "No servers available. Check your subscription in the dashboard",
    notifOffWarn = "Notifications are off — without them the VPN can't be stopped from the shade. Tap to enable",
    noticeRemoteSignout = "This device was disconnected in the account dashboard. Sign in again to continue",
    trafficLowWarn = "Traffic is running out: %s left",
    expiresSoonWarn = "Subscription expires in %s",
    renew = "Renew",
    dayOne = "day",
    dayFew = "days",
    dayMany = "days",
    unitGb = "GB",
    unitMb = "MB",
    settings = "Settings",
    split = "Split tunneling",
    splitDesc = "Hides VPN usage from Russian services",
    addFile = "Add file",
    autoconnect = "Auto-connect",
    autoconnectDesc = "Connect to VPN on launch",
    background = "Background activity",
    backgroundDesc = "Huawei, Honor, Xiaomi and similar skins unload the app from memory and drop the VPN. Lift the restriction — it's a one-time action",
    backgroundDone = "No restrictions",
    notifDisconnect = "Disconnect",
    language = "Language",
    langName = "English",
    logout = "Log out",
    logoutConfirmTitle = "Sure you want to log out?",
    logoutConfirmMessage = "You'll need to enter your account details again",
    yes = "Yes",
    no = "No",
    fileTitle = "Tunneling file",
    fileDesc = "A list of IP subnets that bypass the VPN. Formats: .json or .txt — one entry like 1.2.3.0/24 per line.",
    defaultMeta = "Default",
    entries = "entries",
    chooseFile = "Choose file",
    del = "Delete",
    holdHint = "Press and hold a file to delete it",
    importError = "Couldn't read the file",
    updateChecking = "Checking for updates…",
    updateNone = "You are on the latest version",
    updateCurrent = "Currently installed %s",
    updateAvailable = "Version %s is available",
    updateButton = "Update",
    updateDownloading = "Downloading… %d%%",
    updateInstalling = "Verifying and opening the installer…",
    updateFailed = "The update didn't go through — check your connection and try again",
    updateMandatory = "The VPN won't work without this update",
    version = "Version",
    tgTitle = "Telegram",
    siteTitle = "Our website",
    faqTitle = "FAQ",
    faqSub = "Setup and troubleshooting",
    rateTitle = "Rate the app",
    rateSub = "App Store · Google Play",
    privacy = "Privacy policy",
    terms = "Terms",
    ms = "ms",

    tabConnect = "Connect",
    tabCountries = "Countries",
    tabProfile = "Profile",
    locationLabel = "Location",
    subscriptionLabel = "Plan",
    downloaded = "Received",
    uploaded = "Sent",
    perSession = "this session",
    untilDate = "until %s",
    endsSoon = "ending soon",
    connectingTitle = "Connecting",
    checkingNode = "Checking the node · %s",
    waitingNode = "Waiting for the node…",
    errorTitle = "Couldn't connect",
    errorChip = "Error",
    errorUnknown = "The server isn't responding",
    retry = "Try again",
    changeCountry = "Change country",
    bestServer = "Best server",
    bestServerSub = "We'll pick the fastest one",
    countryTitle = "Country",
    countrySub = "The choice is remembered",
    connect = "Connect",
    yourLogin = "Your login",
    copy = "Copy",
    copied = "Copied",
    cabinet = "Dashboard",
    cabinetSub = "Plans, devices, friends",
    notices = "Notifications",
    noNotices = "Nothing new yet",
    theme = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    sectionConnection = "CONNECTION",
    sectionApp = "APP",
    about = "About",
    supportHeadline = "We answer in 10 minutes",
    supportHours = "Every day, 9:00-23:00 Moscow time",
    writeTelegram = "Message us on Telegram",
    mailTitle = "Email",
    siteAndCabinet = "Website and dashboard",
    noInternet = "No internet",
    noInternetSub = "Check Wi-Fi or mobile data",
    loginTitle = "Sign in",
    loginSub = "Your dashboard login and password",
    loginField = "Login",
    passwordField = "Password",
    showPassword = "Show",
    hidePassword = "Hide",
    register = "Sign up",
    forgotPassword = "Forgot password?",
    notificationsTitle = "Notifications",
    notificationsDesc = "Without them the VPN can't be stopped from the shade",
    autostartTitle = "Start with the system",
    ping = "ms",
    supportTitle = "Support",
    applyDone = "Done",
    splitShort = "RU banks and gov sites go direct",
    guideTitle = "Guide",
    guideSub = "Setup and configuration",
)

fun strings(lang: String): Strings = if (lang == "en") EN else RU
