map $ssl_preread_server_name $prosto_upstream {
    www.google.com   reality_xray;
    default          local_https;
}
upstream reality_xray { server 127.0.0.1:8444; }
upstream local_https  { server 127.0.0.1:4443; }

server {
    listen 443 reuseport;
    listen [::]:443 reuseport;
    ssl_preread on;
    proxy_protocol on;
    proxy_timeout 1h;
    proxy_pass $prosto_upstream;
}
