server_tokens off;

limit_conn_zone $binary_remote_addr zone=prosto_conn:10m;

client_header_timeout 15s;
client_body_timeout   15s;
send_timeout          30s;
keepalive_timeout     30s;
reset_timedout_connection on;

ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
ssl_session_tickets off;
