package com.alisavpn.app

data class Strings(
    val brand: String,
    val back: String,
    val loginSubtitle: String,
    val loginPlaceholder: String,
    val passwordPlaceholder: String,
    val signIn: String,
    val terms: String,
    val errEnterLogin: String,
    val errShortPassword: String,
    val errBadCredentials: String,
    val errBadKey: String,
    val stateOff: String,
    val stateConnecting: String,
    val stateOn: String,
    val tapToConnect: String,
    val server: String,
    val selectServer: String,
    val settings: String,
    val splitTunnel: String,
    val splitTunnelSub: String,
    val exclusionList: String,
    val splitDefaultList: String,
    val resetList: String,
    val resetListSub: String,
    val autoConnect: String,
    val autoConnectSub: String,
    val killSwitch: String,
    val killSwitchSub: String,
    val logging: String,
    val loggingSub: String,
    val language: String,
    val languageValue: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmText: String,
    val yes: String,
    val no: String,
    val listLoaded: String,
    val listLoadFailed: String,
    val support: String,
    val version: String,
    val supportTelegram: String,
    val supportSite: String,
    val supportFaq: String,
    val supportFaqSub: String,
    val footerLinks: String,
)

private val RU = Strings(
    brand = "Алиса VPN",
    back = "Назад",
    loginSubtitle = "Свободный и безопасный интернет",
    loginPlaceholder = "Логин",
    passwordPlaceholder = "Пароль",
    signIn = "Войти",
    terms = "Продолжая, вы принимаете условия сервиса",
    errEnterLogin = "Введите логин",
    errShortPassword = "Пароль слишком короткий",
    errBadCredentials = "Неверный логин или пароль",
    errBadKey = "Не удалось применить ключ. Проверьте ключ и попробуйте ещё раз",
    stateOff = "Отключено",
    stateConnecting = "Подключение…",
    stateOn = "Подключено",
    tapToConnect = "Нажмите, чтобы подключиться",
    server = "Сервер",
    selectServer = "ВЫБЕРИТЕ СЕРВЕР",
    settings = "Настройки",
    splitTunnel = "Раздельное туннелирование",
    splitTunnelSub = "Весь трафик через VPN, кроме сайтов из списка",
    exclusionList = "Список исключений",
    splitDefaultList = "Россия — встроенный список",
    resetList = "Сбросить на список по умолчанию",
    resetListSub = "Россия — встроенный список",
    autoConnect = "Автоподключение",
    autoConnectSub = "Подключаться к VPN при запуске",
    killSwitch = "Kill Switch",
    killSwitchSub = "Блокировать интернет при обрыве VPN",
    logging = "Логирование",
    loggingSub = "Сохранять журнал для диагностики",
    language = "Язык",
    languageValue = "Русский",
    logout = "Выйти из аккаунта",
    logoutConfirmTitle = "Уверены, что хотите выйти?",
    logoutConfirmText = "Для входа понадобится снова ввести ключ доступа",
    yes = "Да",
    no = "Нет",
    listLoaded = "Список загружен",
    listLoadFailed = "Нужен JSON-список IP-подсетей (CIDR) — в файле их не нашлось",
    support = "Поддержка",
    version = "Версия",
    supportTelegram = "Поддержка в Telegram",
    supportSite = "Наш сайт",
    supportFaq = "Частые вопросы",
    supportFaqSub = "Как настроить и решить проблемы",
    footerLinks = "Политика конфиденциальности · Условия",
)

private val EN = Strings(
    brand = "Алиса VPN",
    back = "Back",
    loginSubtitle = "Free and secure internet",
    loginPlaceholder = "Login",
    passwordPlaceholder = "Password",
    signIn = "Sign in",
    terms = "By continuing, you accept the terms of service",
    errEnterLogin = "Enter your login",
    errShortPassword = "Password is too short",
    errBadCredentials = "Wrong login or password",
    errBadKey = "Couldn't apply the key. Check it and try again",
    stateOff = "Disconnected",
    stateConnecting = "Connecting…",
    stateOn = "Connected",
    tapToConnect = "Tap to connect",
    server = "Server",
    selectServer = "SELECT SERVER",
    settings = "Settings",
    splitTunnel = "Split tunneling",
    splitTunnelSub = "All traffic through VPN, except the listed sites",
    exclusionList = "Exclusion list",
    splitDefaultList = "Russia — built-in list",
    resetList = "Reset to default list",
    resetListSub = "Russia — built-in list",
    autoConnect = "Auto-connect",
    autoConnectSub = "Connect to VPN on app start",
    killSwitch = "Kill Switch",
    killSwitchSub = "Block the internet if VPN drops",
    logging = "Logging",
    loggingSub = "Keep a diagnostic log",
    language = "Language",
    languageValue = "English",
    logout = "Log out",
    logoutConfirmTitle = "Are you sure you want to log out?",
    logoutConfirmText = "You'll need to enter the access key again to sign in",
    yes = "Yes",
    no = "No",
    listLoaded = "List loaded",
    listLoadFailed = "Expected a JSON list of IP subnets (CIDR) — none found in the file",
    support = "Support",
    version = "Version",
    supportTelegram = "Telegram support",
    supportSite = "Our website",
    supportFaq = "FAQ",
    supportFaqSub = "How to set up and troubleshoot",
    footerLinks = "Privacy Policy · Terms",
)

fun strings(lang: String): Strings = if (lang == "en") EN else RU
