package com.prostovpn.desktop

data class Strings(
    val tagline: String,
    val loginPlaceholder: String,
    val passwordPlaceholder: String,
    val signIn: String,
    val signingIn: String,
    val signInDone: String,
    val errEmptyLogin: String,
    val errShortPassword: String,
    // Отказы во входе. Текст панели сюда больше не попадает: он написан
    // по-русски, а интерфейс бывает английским.
    val errBadCredentials: String,
    val errAccountBlocked: String,
    val errAccountDisabled: String,
    val errTooManyTries: String,
    val errTooManyTriesIn: String,
    val errPanelUnreachable: String,
    val errPanelFault: String,
    val errNoKey: String,
    val errBadConfig: String,
    val errNoBackend: String,
    val errElevation: String,
    val errAddressInUse: String,
    val errTunnel: String,
    val errNoHandshake: String,
    val errUnsupportedObfuscation: String,
    val errHsSilence: String,
    val errHsPortClosed: String,
    val errHsHeader: String,
    val errHsRejected: String,
    val errHsBlackhole: String,
    val errHsKillSwitch: String,
    val errLogHint: String,
    val errTunnelDropped: String,
    val noticeRemoteSignout: String,
    val errDisconnectStuck: String,
    val errUnsupportedOs: String,
    val termsPrefix: String,
    val termsLink: String,

    val connected: String,
    val connectingTxt: String,
    val disconnectingTxt: String,
    val disconnected: String,
    val tapToConnect: String,
    val chooseServer: String,

    val settings: String,

    // Трей: приложение прячется туда по крестику и живёт дальше
    val trayOpen: String,
    val trayQuit: String,
    val trayHint: String,
    val trayConnect: String,
    val trayDisconnect: String,
    val trayStatusConnecting: String,
    val trayStatusDisconnecting: String,
    val trayServer: String,
    val trayNoServers: String,
    val split: String,
    val splitDesc: String,
    val addFile: String,
    val autostart: String,
    val autostartDesc: String,
    val autoconnect: String,
    val autoconnectDesc: String,
    val logging: String,
    val loggingDesc: String,

    // Подписка на главном экране
    val subEndsIn: String,
    val subEnded: String,
    val renewNow: String,
    val trafficLowTitle: String,
    val trafficOverTitle: String,
    val trafficUsed: String,
    val outOf: String,
    val dayOne: String,
    val dayFew: String,
    val dayMany: String,
    val language: String,
    val langName: String,
    val logout: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val yes: String,
    val no: String,

    val fileTitle: String,
    val fileDesc: String,
    val defaultMeta: String,
    val entries: String,
    val chooseFile: String,
    val del: String,
    val holdHint: String,
    val rightClickHint: String,
    val importError: String,

    val updateAvailable: String,
    val updateNone: String,
    val updateCurrent: String,
    val updateButton: String,
    val updateDownloading: String,
    val updateDownloadingShort: String,
    val updateFailed: String,
    val tgTitle: String,
    val siteTitle: String,
    val faqTitle: String,
    val faqSub: String,
    val rateTitle: String,
    val rateSub: String,
    val privacy: String,
    val terms: String,

    val ms: String,
)

private val RU = Strings(
    tagline = "Свободный и безопасный интернет",
    loginPlaceholder = "Логин",
    passwordPlaceholder = "Пароль",
    signIn = "Войти",
    signingIn = "Подключение…",
    signInDone = "✓ Готово",
    errEmptyLogin = "Введите логин",
    errShortPassword = "Пароль слишком короткий",
    errBadCredentials = "Неверный логин или пароль",
    errAccountBlocked = "Доступ заблокирован. Напишите в поддержку",
    errAccountDisabled = "Доступ отключён. Напишите в поддержку",
    errTooManyTries = "Слишком много попыток входа. Попробуйте позже",
    errTooManyTriesIn = "Слишком много попыток входа. Попробуйте через %d мин",
    errPanelUnreachable = "Не удалось связаться с сервером. Проверьте интернет и повторите",
    errPanelFault = "Сервер не отвечает. Попробуйте позже",
    errNoKey = "Нет доступных серверов. Войдите в аккаунт или продлите подписку",
    errBadConfig = "Сервер прислал конфигурацию, которую не удалось применить",
    errNoBackend = "Не найден движок туннеля Prosto VPN. Переустановите приложение",
    errElevation = "Для подключения нужны права администратора",
    errAddressInUse = "Этим же ключом уже подключён другой VPN — отключите его. Адрес туннеля занят адаптером",
    errTunnel = "Не удалось поднять туннель",
    errNoHandshake = "Сервер не отвечает. Проверьте ключ или выберите другой сервер",
    errUnsupportedObfuscation = "Ключ использует неподдерживаемую маскировку:",
    errHsSilence = "Сервер молчит: он выключен, или сеть блокирует подключение. Попробуйте другую сеть",
    errHsPortClosed = "Сервер отклоняет подключение: VPN на этом порту не запущен",
    errHsHeader = "Ответ сервера не распознан: маскировка в ключе не совпадает с сервером. Обновите ключ",
    errHsRejected = "Сервер отвечает, но пакеты не проходят проверку: ключ устарел или не от этого сервера",
    errHsBlackhole = "Windows не выпустил пакеты наружу: не выбран сетевой адаптер. Переподключитесь к сети и повторите",
    errHsKillSwitch = "Сервер молчал: подключение заглушили блокирующие правила брандмауэра. Обычно это сторонние обходы блокировок (zapret и подобные) — закройте их и повторите",
    errLogHint = "Подробности: %LOCALAPPDATA%\\ProstoVPN\\tunnel.log",
    errTunnelDropped = "Соединение с VPN прервалось",
    noticeRemoteSignout = "Это устройство отключили в личном кабинете. Чтобы вернуться, войдите снова",
    errDisconnectStuck = "Туннель не снялся — трафик может всё ещё идти через VPN. Перезапустите приложение",
    errUnsupportedOs = "Подключение поддерживается только на Windows",
    termsPrefix = "Продолжая, вы принимаете ",
    termsLink = "условия сервиса",
    connected = "Подключено",
    connectingTxt = "Подключение…",
    disconnectingTxt = "Отключение…",
    disconnected = "Отключено",
    tapToConnect = "Нажмите, чтобы подключиться",
    chooseServer = "ВЫБЕРИТЕ СЕРВЕР",
    settings = "Настройки",
    trayOpen = "Открыть",
    trayQuit = "Выйти",
    trayHint = "Приложение продолжает работать — значок остался в трее, рядом с часами",
    trayConnect = "Подключиться",
    trayDisconnect = "Отключиться",
    trayStatusConnecting = "Подключение…",
    trayStatusDisconnecting = "Отключение…",
    trayServer = "Сервер",
    trayNoServers = "Нет серверов",
    split = "Раздельное туннелирование",
    splitDesc = "РФ-сервисы идут мимо VPN. Kill Switch при этом не работает",
    addFile = "Добавить файл",
    autostart = "Автозапуск",
    autostartDesc = "Запускать приложение при старте устройства",
    autoconnect = "Автоподключение",
    autoconnectDesc = "Подключаться к VPN при запуске",
    logging = "Логирование",
    loggingDesc = "Сохранять журнал для диагностики",
    language = "Язык",
    langName = "Русский",
    logout = "Выйти из аккаунта",
    logoutConfirmTitle = "Уверены, что хотите выйти?",
    logoutConfirmMessage = "Для входа понадобится снова ввести данные аккаунта",
    yes = "Да",
    no = "Нет",
    fileTitle = "Файл туннелирования",
    fileDesc = "Список сайтов и приложений, которые идут через VPN. Форматы: .json или .txt — по одному домену или названию приложения на строку.",
    defaultMeta = "По умолчанию",
    entries = "записей",
    chooseFile = "Выбрать файл",
    del = "Удалить",
    holdHint = "Удерживайте файл, чтобы удалить его",
    rightClickHint = "Правый клик по файлу — удалить",
    importError = "Не удалось прочитать файл",
    updateAvailable = "Доступна версия %s",
    updateNone = "Установлена последняя версия",
    updateCurrent = "Сейчас установлена %s",
    updateButton = "Обновить",
    updateDownloading = "Скачиваем… %d%%",
    updateDownloadingShort = "Скачиваем…",
    updateFailed = "Не удалось скачать обновление",
    subEndsIn = "Подписка заканчивается через",
    subEnded = "Подписка закончилась",
    renewNow = "Продлить подписку",
    trafficLowTitle = "Трафика осталось мало:",
    trafficOverTitle = "Трафик закончился — продлите подписку",
    trafficUsed = "Израсходовано",
    outOf = "из",
    dayOne = "день",
    dayFew = "дня",
    dayMany = "дней",
    tgTitle = "Telegram",
    siteTitle = "Наш сайт",
    faqTitle = "Частые вопросы",
    faqSub = "Как настроить и решить проблемы",
    rateTitle = "Оценить приложение",
    rateSub = "App Store · Google Play",
    privacy = "Политика конфиденциальности",
    terms = "Условия",
    ms = "мс",
)

private val EN = Strings(
    tagline = "Free and secure internet",
    loginPlaceholder = "Login",
    passwordPlaceholder = "Password",
    signIn = "Sign in",
    signingIn = "Connecting…",
    signInDone = "✓ Done",
    errEmptyLogin = "Enter your login",
    errShortPassword = "Password is too short",
    errBadCredentials = "Wrong login or password",
    errAccountBlocked = "Access is blocked. Contact support",
    errAccountDisabled = "Access is turned off. Contact support",
    errTooManyTries = "Too many sign-in attempts. Try again later",
    errTooManyTriesIn = "Too many sign-in attempts. Try again in %d min",
    errPanelUnreachable = "Couldn't reach the server. Check your connection and retry",
    errPanelFault = "The server is not responding. Try again later",
    errNoKey = "No servers available. Sign in or renew your subscription",
    errBadConfig = "The server sent a configuration that could not be applied",
    errNoBackend = "Prosto VPN tunnel engine not found. Reinstall the app",
    errElevation = "Administrator rights are required to connect",
    errAddressInUse = "Another VPN is already connected with this key — disconnect it. The tunnel address is held by adapter",
    errTunnel = "Couldn't bring the tunnel up",
    errNoHandshake = "The server is not responding. Check the key or pick another server",
    errUnsupportedObfuscation = "The key uses unsupported obfuscation:",
    errHsSilence = "The server is silent: it's down, or the network blocks the connection. Try another network",
    errHsPortClosed = "The server rejects the connection: no VPN is listening on this port",
    errHsHeader = "The server's reply is unrecognized: the key's obfuscation doesn't match the server. Update the key",
    errHsRejected = "The server replies, but packets fail verification: the key is stale or for another server",
    errHsBlackhole = "Windows didn't let packets out: no network adapter was selected. Reconnect to the network and retry",
    errHsKillSwitch = "The server stayed silent: the connection was killed by blocking firewall rules. Usually third-party circumvention tools (zapret and similar) — close them and retry",
    errLogHint = "Details: %LOCALAPPDATA%\\ProstoVPN\\tunnel.log",
    errTunnelDropped = "VPN connection dropped",
    noticeRemoteSignout = "This device was disconnected from the account. Sign in again to continue",
    errDisconnectStuck = "The tunnel did not come down — traffic may still go through the VPN. Restart the app",
    errUnsupportedOs = "Connecting is supported on Windows only",
    termsPrefix = "By continuing you accept the ",
    termsLink = "terms of service",
    connected = "Connected",
    connectingTxt = "Connecting…",
    disconnectingTxt = "Disconnecting…",
    disconnected = "Disconnected",
    tapToConnect = "Tap to connect",
    chooseServer = "CHOOSE A SERVER",
    settings = "Settings",
    trayOpen = "Open",
    trayQuit = "Quit",
    trayHint = "The app keeps running — its icon stays in the tray, next to the clock",
    trayConnect = "Connect",
    trayDisconnect = "Disconnect",
    trayStatusConnecting = "Connecting…",
    trayStatusDisconnecting = "Disconnecting…",
    trayServer = "Server",
    trayNoServers = "No servers",
    split = "Split tunneling",
    splitDesc = "Russian services bypass the VPN. Kill Switch is off then",
    addFile = "Add file",
    autostart = "Launch at startup",
    autostartDesc = "Open the app when the device starts",
    autoconnect = "Auto-connect",
    autoconnectDesc = "Connect to VPN on launch",
    logging = "Logging",
    loggingDesc = "Keep a diagnostics log",
    language = "Language",
    langName = "English",
    logout = "Log out",
    logoutConfirmTitle = "Sure you want to log out?",
    logoutConfirmMessage = "You'll need to enter your account details again",
    yes = "Yes",
    no = "No",
    fileTitle = "Tunneling file",
    fileDesc = "A list of sites and apps routed through the VPN. Formats: .json or .txt — one domain or app name per line.",
    defaultMeta = "Default",
    entries = "entries",
    chooseFile = "Choose file",
    del = "Delete",
    holdHint = "Press and hold a file to delete it",
    rightClickHint = "Right-click a file to delete it",
    importError = "Couldn't read the file",
    updateAvailable = "Version %s is available",
    updateNone = "You are on the latest version",
    updateCurrent = "Currently installed %s",
    updateButton = "Update",
    updateDownloading = "Downloading… %d%%",
    updateDownloadingShort = "Downloading…",
    updateFailed = "Could not download the update",
    subEndsIn = "Subscription ends in",
    subEnded = "Subscription has ended",
    renewNow = "Renew subscription",
    trafficLowTitle = "Traffic running low:",
    trafficOverTitle = "You are out of traffic — renew your subscription",
    trafficUsed = "Used",
    outOf = "of",
    dayOne = "day",
    dayFew = "days",
    dayMany = "days",
    tgTitle = "Telegram",
    siteTitle = "Our website",
    faqTitle = "FAQ",
    faqSub = "Setup and troubleshooting",
    rateTitle = "Rate the app",
    rateSub = "App Store · Google Play",
    privacy = "Privacy policy",
    terms = "Terms",
    ms = "ms",
)

fun strings(lang: String): Strings = if (lang == "en") EN else RU
